In [1]:

import cv2
import os
  
import numpy as np
  
root_path = "./RobomasterNumData"
dir = root_path+"1L"+"/"
count = 0
for root,dir,files in os.walk(dir):
    count = count+1
    print(count)
 # for file in files:
 #  srcImg = cv2.imread(root_path+"images"+"/"+str(file))
 #  roiImg = srcImg[36:521, 180:745]
 #  cv2.imwrite(root_path+"Image"+"/"+str(file),roiImg)
 #  count +=1
 #  if count%400==0:
 #   print count



In [ ]:


import os
import cv2
import numpy as np
fileList = os.listdir(os.getcwd()+"/RobomasterNumData/1L/")
print(len(fileList))
label = np.zeros(50*4,1)
for i in range(5):
    for j in range(50):
        label[i*5+j] = i
        print(label[i*5+j])
        
for i in range(len(fileList)):
    print(i,fileList[i])
    I = cv2.imread(os.getcwd()+"/RobomasterNumData/1L/"+fileList[i])
    I = cv2.resize(I,(640,480))
    I = cv2.cvtColor(I,cv2.COLOR_BGR2BGRA)
    cv2.imshow("1",I)
    cv2.waitKey(30)
cv2.waitKey(0)


In [ ]:
import os
import cv2
import numpy as np
label = np.zeros(50*4,1)
for i in range(5):
    for j in range(50):
        label[i*5+j] = i
        print(label[i*5+j])
        

In [12]:
import torch
import torchvision
import numpy 
from torch.autograd import Variable
x1 = Variable(torch.rand(3,5))
x2 = Variable(torch.rand(4,5))
x = torch.cat((x1,x2), 0)
print(x.size())


a = torch.rand(3, 4)

b = torch.rand(3, 4)

d = torch.stack((a, b), 0)

# d = torch.cat((d, b), 0)

print(a.shape)

print(b.shape)

print(d.shape)

s = torch.rand(2,1,5,10)
sb = torch.rand(1,5,10)
print(sb)
print(s)
s[0,:,:,:] = sb
print(s)




torch.Size([7, 5])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 3, 4])
tensor([[[0.7630, 0.3889, 0.5354, 0.5353, 0.5095, 0.0193, 0.6594, 0.0356,
          0.2208, 0.9626],
         [0.2814, 0.9060, 0.3370, 0.0939, 0.6028, 0.4939, 0.3862, 0.2887,
          0.7670, 0.1757],
         [0.4371, 0.2997, 0.3695, 0.8947, 0.7703, 0.9093, 0.9704, 0.7525,
          0.8538, 0.0882],
         [0.7632, 0.6019, 0.8396, 0.1213, 0.0185, 0.6125, 0.5356, 0.9219,
          0.7550, 0.9672],
         [0.2715, 0.2189, 0.8767, 0.4081, 0.7304, 0.1395, 0.8011, 0.2562,
          0.6701, 0.1219]]])
tensor([[[[0.2470, 0.0702, 0.8613, 0.8108, 0.8075, 0.7306, 0.0878, 0.1724,
           0.3447, 0.5379],
          [0.1537, 0.8676, 0.8679, 0.9250, 0.1647, 0.8131, 0.0596, 0.3736,
           0.3834, 0.4319],
          [0.5711, 0.3128, 0.0747, 0.0344, 0.0046, 0.0657, 0.4101, 0.0940,
           0.2857, 0.7042],
          [0.2434, 0.2292, 0.7464, 0.8338, 0.3429, 0.0567, 0.7433, 0.1849,
           0.8850, 0.5763],
  

In [15]:
import torch
import torchvision
import numpy 
from torch.autograd import Variable
test = torch.rand(2,1,5,3)
print(test)
test = test*10
print(test)
test = test/10.0
print(test)

tensor([[[[0.9202, 0.8113, 0.1767],
          [0.7482, 0.2651, 0.9744],
          [0.5125, 0.6433, 0.8847],
          [0.1206, 0.6098, 0.0472],
          [0.3083, 0.2332, 0.5650]]],


        [[[0.5043, 0.5506, 0.9280],
          [0.3588, 0.1529, 0.5226],
          [0.5789, 0.9386, 0.9012],
          [0.3978, 0.4213, 0.6891],
          [0.8053, 0.8238, 0.3409]]]])
tensor([[[[9.2021, 8.1131, 1.7672],
          [7.4819, 2.6508, 9.7441],
          [5.1254, 6.4335, 8.8466],
          [1.2055, 6.0979, 0.4717],
          [3.0833, 2.3320, 5.6496]]],


        [[[5.0427, 5.5064, 9.2796],
          [3.5877, 1.5293, 5.2256],
          [5.7891, 9.3864, 9.0124],
          [3.9783, 4.2128, 6.8911],
          [8.0525, 8.2380, 3.4093]]]])
tensor([[[[0.9202, 0.8113, 0.1767],
          [0.7482, 0.2651, 0.9744],
          [0.5125, 0.6433, 0.8847],
          [0.1206, 0.6098, 0.0472],
          [0.3083, 0.2332, 0.5650]]],


        [[[0.5043, 0.5506, 0.9280],
          [0.3588, 0.1529, 0.5226],
          